version: "3.0"
services:
  elasticsearch:
    container_name: elasticsearch-local
    image: tunnm/docker-es-cococ-tokenizer:7.12.1
    ports:
      - "9200:9200"
    restart: unless-stopped
    environment:
      ES_JAVA_OPTS: "-Xmx4g -Xms4g"
      bootstrap.memory_lock: "true"
      discovery.type: "single-node"
      http.host: "0.0.0.0"
      action.auto_create_index: ".watches,.triggered_watches,.watcher-history-*"
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
      memlock:
        hard: -1
        soft: -1
  kibana:
    container_name: kb-container
    restart: unless-stopped
    image: docker.elastic.co/kibana/kibana:7.12.0
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    depends_on:
      - elasticsearch
    ports:
      - 5601:5601

