version: '3'
services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2019-latest 
    container_name: mssql-local
    volumes:
      - ./mssql_data:/var/opt/mssql
    ports:
      - 1433:1433
    environment:
      MSSQL_SA_PASSWORD: 123456
volumes:
  mssql_data:
