version: '3'
services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2019-latest 
    container_name: mssql-local
    restart: no
    volumes:
      - ./mssql_data:/var/opt/mssql/data
    ports:
      - 1433:1433
    environment:
      MSSQL_SA_PASSWORD: manh123456
      ACCEPT_EULA: Y
