version: '3'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.8.1
    container_name: es-local
    restart: no
    environment:
      - node.name=elasticsearch
      - discovery.seed_hosts=elasticsearch
      - cluster.initial_master_nodes=elasticsearch
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9200:9200
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:9200"]
      interval: 30s
      timeout: 10s
      retries: 5

  # kibana:
  #   image: docker.elastic.co/kibana/kibana:7.8.1
  #   restart: no
  #   container_name: kibana-local
  #   ports:
  #     - 5601:5601
  #   depends_on:
  #     elasticsearch:
  #       condition: service_healthy

# wsl -d docker-desktop
# sysctl -w vm.max_map_count=262144

