version: '3'
services:
  mysql:
    image: mysql:8.0
    container_name: mysql-local
    restart: no
    volumes:
      - ./mysql_data:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: manh123456
volumes:
  mysql_data:
