version: '3'
services:
  mysql:
    image: mysql:latest
    container_name: mysql-local
    volumes:
      - ./mysql_data:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: 123456
volumes:
  mysql_data:
