version: '3'
services:
  postgres:
    image: postgres:14
    container_name: postgres-local
    restart: no
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: manh123456
    networks:
      - db
volumes:
  postgres_data:

networks: 
  db: 
    external: true