version: '3'
services:
  mongo:
    image: mongo:latest
    restart: unless-stopped
    container_name: mongo-local
    volumes:
      - ./mongo_data:/data/db
    ports:
      - 27017:27017
volumes:
  mongo_data:
